localPlanner:
  ros__parameters:
    vehicleLength: 0.25
    vehicleWidth: 0.25
    laserVoxelSize: 0.025
    terrainVoxelSize: 0.025
    useTerrainAnalysis: true
    checkObstacle: true
    checkRotObstacle: false
    adjacentRange: 4.25
    obstacleHeightThre: 0.05
    groundHeightThre: 0.05
    costHeightThre: 0.1
    costScore: 0.02
    useCost: false
    pointPerPathThre: 2
    minRelZ: -0.25
    maxRelZ: 1.0
    dirWeight: 0.02
    dirThre: 90.0
    dirToVehicle: false
    pathScale: 1.25
    minPathScale: 0.5
    pathScaleStep: 0.25
    pathScaleBySpeed: true
    minPathRange: 1.0
    pathRangeStep: 0.5
    pathRangeBySpeed: true
    pathCropByGoal: true
    joyToCheckObstacleDelay: 5.0
    goalClearRange: 0.5
    goalX: 0.0
    goalY: 0.0